# Magento's Database
magento_database:
    type: mariadb:10.3
    disk: 2048

# Magento's cache & session redis instance
magento_redis:
    type: redis:6.2

# Magento's Elasticsearch-compatible OpenSearch instance.
magento_search:
    # Magento 2.3.7 is also compatible with elasticsearch:7.9
    type: opensearch:1.2
    disk: 256
    configuration:
        plugins:
            - analysis-icu
            - analysis-phonetic
